/// CML Sponge cipher test suite.
///
/// Covers:
///   - Cross-validation against canonical Python test vectors (TV1–TV4)
///   - Complement symmetry: all-zero and all-FF keys must diverge
///   - Encrypt / decrypt round-trip
///   - IV sensitivity: 1-bit IV change → different keystream
///   - Key sensitivity: 1-bit key change → different keystream
///   - Stream consistency: two equal-length requests == one combined request
///   - Empty keystream: no-op
///   - Multi-block output: >64-byte keystream is contiguous and deterministic
///   - Zeroize-on-drop: state is accessible before drop (compile-level sanity)
///   - Reduced-round variant: same init, 1-round vs 8-round → different output

use au79_crypto::cml_sponge::{cipher_init, cipher_init_r, keystream, keystream_r,
                               encrypt_in_place, decrypt_in_place};

// ── Helpers ───────────────────────────────────────────────────────────────────

fn ks(key: &[u8; 32], iv: &[u8; 16], len: usize) -> Vec<u8> {
    let mut state = cipher_init(key, iv);
    let mut out = vec![0u8; len];
    keystream(&mut state, &mut out);
    out
}

fn ks_r(key: &[u8; 32], iv: &[u8; 16], len: usize, rounds: usize) -> Vec<u8> {
    let mut state = cipher_init_r(key, iv, rounds);
    let mut out = vec![0u8; len];
    keystream_r(&mut state, &mut out, rounds);
    out
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

// ── Canonical test vectors ────────────────────────────────────────────────────
// Generated by the fixed Python reference (complement symmetry bug resolved).
// TV1: incremental key/IV
// TV2: all-zero key/IV
// TV3: all-FF key/IV   (MUST differ from TV2 — complement symmetry fix)
// TV4: repeating 0x42 key, 0x13 IV

#[test]
fn tv1_incremental_key_iv() {
    let key: [u8; 32] = core::array::from_fn(|i| i as u8);
    let iv:  [u8; 16] = core::array::from_fn(|i| i as u8);
    // Generated by the fixed Python reference (with Stafford Mix13 output finalizer).
    let expected = "4308614da999d185fd8468294705b7af480f99a84184d32f8596abcf4a6dfce2\
                    bfb98bdcce2967d6151dc6b89fbaa0ffba56f0490845e47fb35e6227035a85cc";
    let got = ks(&key, &iv, 64);
    assert_eq!(hex(&got), expected, "TV1 mismatch");
}

#[test]
fn tv2_all_zero_key_iv() {
    let key = [0u8; 32];
    let iv  = [0u8; 16];
    let expected = "8f5f8904705abcb7d6c716211ccce7c19df7cbb57e8e745725bf7053b40213d2\
                    dd5e13b0ec4abe17d686ea35f6a00355611e1d6994bcfd9a77b50a73a4a4bd69";
    let got = ks(&key, &iv, 64);
    assert_eq!(hex(&got), expected, "TV2 mismatch");
}

#[test]
fn tv3_all_ff_key_iv() {
    let key = [0xFFu8; 32];
    let iv  = [0xFFu8; 16];
    let expected = "f21de442eb45df36fb35d5ab83f80c74c8dbc179bfe640193074c5ffdf6c7430\
                    f218a4d5f48d3104574fca49c01ad6b6661c8ae77948b6a5114e9b186bd6a484";
    let got = ks(&key, &iv, 64);
    assert_eq!(hex(&got), expected, "TV3 mismatch");
    // Complement symmetry fix: all-FF must differ from all-zero.
    assert_ne!(hex(&got), hex(&ks(&[0u8; 32], &[0u8; 16], 64)),
        "TV3 must differ from TV2 (complement symmetry bug)");
}

#[test]
fn tv4_repeating_key_iv() {
    let key = [0x42u8; 32];
    let iv  = [0x13u8; 16];
    let expected = "1d23bcada3742497edffeb073e938d7f2ac556036fdbf16f8577bdf9a5acf6e8\
                    d01ca25260775472752c4b359f3042753b554138acb6272198e8abbab77804a7";
    let got = ks(&key, &iv, 64);
    assert_eq!(hex(&got), expected, "TV4 mismatch");
}

// ── Complement symmetry (core invariant of the fix) ───────────────────────────

#[test]
fn complement_symmetry_broken() {
    let key_zero = [0x00u8; 32];
    let key_ff   = [0xFFu8; 32];
    let iv_zero  = [0x00u8; 16];
    let iv_ff    = [0xFFu8; 16];

    let ks_00 = ks(&key_zero, &iv_zero, 64);
    let ks_ff = ks(&key_ff,   &iv_ff,   64);

    assert_ne!(ks_00, ks_ff,
        "all-zero and all-FF keys must produce distinct keystreams (complement symmetry bug present)");
}

#[test]
fn complement_symmetry_key_only() {
    let key_zero = [0x00u8; 32];
    let key_ff   = [0xFFu8; 32];
    let iv       = [0xABu8; 16];

    let s_zero = ks(&key_zero, &iv, 64);
    let s_ff   = ks(&key_ff,   &iv, 64);
    assert_ne!(s_zero, s_ff, "complemented key must produce different keystream");
}

// ── Encrypt / decrypt round-trip ──────────────────────────────────────────────

#[test]
fn round_trip_encrypt_decrypt() {
    let key: [u8; 32] = core::array::from_fn(|i| (i * 7 + 3) as u8);
    let iv:  [u8; 16] = core::array::from_fn(|i| (i * 13 + 5) as u8);

    let plaintext = b"CML Sponge round-trip test 12345";
    let mut buf = plaintext.to_vec();

    let mut enc_state = cipher_init(&key, &iv);
    encrypt_in_place(&mut enc_state, &mut buf);
    assert_ne!(buf, plaintext, "ciphertext must differ from plaintext");

    let mut dec_state = cipher_init(&key, &iv);
    decrypt_in_place(&mut dec_state, &mut buf);
    assert_eq!(buf, plaintext, "decrypted plaintext must match original");
}

#[test]
fn round_trip_empty() {
    let key = [0x55u8; 32];
    let iv  = [0xAAu8; 16];
    let mut buf: Vec<u8> = vec![];
    let mut state = cipher_init(&key, &iv);
    encrypt_in_place(&mut state, &mut buf);
    assert!(buf.is_empty());
}

#[test]
fn round_trip_one_byte() {
    let key = [0x01u8; 32];
    let iv  = [0x02u8; 16];
    let mut buf = vec![0xA5u8];
    let mut enc = cipher_init(&key, &iv);
    encrypt_in_place(&mut enc, &mut buf);
    let mut dec = cipher_init(&key, &iv);
    decrypt_in_place(&mut dec, &mut buf);
    assert_eq!(buf[0], 0xA5);
}

#[test]
fn round_trip_large() {
    let key = [0xDEu8; 32];
    let iv  = [0xADu8; 16];
    let plaintext: Vec<u8> = (0..10_000).map(|i| (i % 256) as u8).collect();
    let mut buf = plaintext.clone();
    let mut enc = cipher_init(&key, &iv);
    encrypt_in_place(&mut enc, &mut buf);
    assert_ne!(buf, plaintext);
    let mut dec = cipher_init(&key, &iv);
    decrypt_in_place(&mut dec, &mut buf);
    assert_eq!(buf, plaintext);
}

// ── Key / IV sensitivity ──────────────────────────────────────────────────────

#[test]
fn key_sensitivity_one_bit() {
    let iv = [0u8; 16];
    let key_a = [0u8; 32];
    let mut key_b = [0u8; 32];
    key_b[0] ^= 0x01; // flip one bit

    let a = ks(&key_a, &iv, 64);
    let b = ks(&key_b, &iv, 64);
    assert_ne!(a, b, "1-bit key change must change keystream");

    // rough avalanche: >25% bits differ
    let differing: usize = a.iter().zip(b.iter())
        .map(|(x, y)| (x ^ y).count_ones() as usize)
        .sum();
    assert!(differing > 128, "expected >128 bit differences, got {}", differing);
    let _ = key_a; // zero-initialize is intentional
}

#[test]
fn iv_sensitivity_one_bit() {
    let key = [0x99u8; 32];
    let iv_a = [0u8; 16];
    let mut iv_b = [0u8; 16];
    iv_b[15] ^= 0x80; // flip high bit of last byte

    let a = ks(&key, &iv_a, 64);
    let b = ks(&key, &iv_b, 64);
    assert_ne!(a, b, "1-bit IV change must change keystream");
}

// ── Stream consistency ────────────────────────────────────────────────────────

#[test]
fn stream_consistency_split_vs_combined() {
    let key = [0x77u8; 32];
    let iv  = [0x33u8; 16];

    // Single request for 200 bytes
    let combined = ks(&key, &iv, 200);

    // Two sequential requests: 100 + 100
    let mut state = cipher_init(&key, &iv);
    let mut part1 = vec![0u8; 100];
    let mut part2 = vec![0u8; 100];
    keystream(&mut state, &mut part1);
    keystream(&mut state, &mut part2);

    assert_eq!(combined[..100], part1[..]);
    assert_eq!(combined[100..], part2[..]);
}

#[test]
fn stream_consistency_byte_by_byte() {
    let key = [0x11u8; 32];
    let iv  = [0x22u8; 16];

    let combined = ks(&key, &iv, 65); // crosses a 64-byte block boundary

    let mut state = cipher_init(&key, &iv);
    let mut out = vec![0u8; 1];
    for i in 0..65 {
        keystream(&mut state, &mut out);
        assert_eq!(out[0], combined[i], "byte {} mismatch in byte-by-byte stream", i);
    }
}

// ── Multi-block determinism ───────────────────────────────────────────────────

#[test]
fn multi_block_determinism() {
    let key = [0xFEu8; 32];
    let iv  = [0xDCu8; 16];

    let a = ks(&key, &iv, 256);
    let b = ks(&key, &iv, 256);
    assert_eq!(a, b, "same key/IV must produce identical keystream across two calls");
}

#[test]
fn multi_block_no_period() {
    // 640 bytes = 10 × 64-byte blocks.  Verify no naive period ≤ 64 bytes.
    let key = [0xBEu8; 32];
    let iv  = [0xEFu8; 16];
    let out = ks(&key, &iv, 640);

    let block0 = &out[0..64];
    for i in 1..10 {
        assert_ne!(block0, &out[i * 64..(i + 1) * 64],
            "keystream block {} equals block 0 — detected naive period", i);
    }
}

// ── Reduced-round variant ─────────────────────────────────────────────────────

#[test]
fn reduced_round_differs_from_full() {
    let key = [0x12u8; 32];
    let iv  = [0x34u8; 16];

    let full     = ks_r(&key, &iv, 64, 8); // 8 rounds (standard)
    let reduced4 = ks_r(&key, &iv, 64, 4); // 4 rounds
    let reduced1 = ks_r(&key, &iv, 64, 1); // 1 round

    assert_ne!(full, reduced4, "4-round output must differ from 8-round");
    assert_ne!(full, reduced1, "1-round output must differ from 8-round");
    assert_ne!(reduced4, reduced1, "4-round and 1-round must differ");
}

#[test]
fn reduced_round_is_deterministic() {
    let key = [0xABu8; 32];
    let iv  = [0xCDu8; 16];

    let a = ks_r(&key, &iv, 128, 3);
    let b = ks_r(&key, &iv, 128, 3);
    assert_eq!(a, b, "reduced-round keystream must be deterministic");
}
